name: Release

concurrency: release

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: 'CI'
    uses: ./.github/workflows/ci.yml

  semantic-release:
    needs: [ci]
    runs-on: ubuntu-latest
    name: 'Semantic Release'
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm build

      # - name: Semantic Release
      #   run: pnpm semantic-release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
